version: '3.8'

services:
  verifier:
    build: .
    container_name: aur_verifier
    restart: always
    expose:
      - "5000"
    networks:
      - aur_net

  nginx:
    image: nginx:alpine
    container_name: aur_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - verifier
    networks:
      - aur_net

networks:
  aur_net:
    driver: bridge